# Generated by Django 5.0.2 on 2024-05-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_tasktitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktitle",
            name="task_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_titles",
                to="tasks.taskgroup",
            ),
            preserve_default=False,
        ),
    ]
